### ISSUE TITLE
Design do fluxo do usuário

### ISSUE THREAD

**Issue by mabemoreira** [mabemoreira/LearningPath#6]
Desenvolvimento do fluxo inicial do usuário:
- Página de apresentação do produto
- Páginas falando sobre a equipe e sobre o produto
- Fluxo de login e criação de conta

**Comment by THdeCamargoJ** [comment]
Finalizado o fluxo de usuário: [protótipo Figma](https://www.figma.com/proto/RcMQUyH6VRXKYcOhMi83Ps/Learning-Path?node-id=6-2&node-type=SECTION&t=nyxq2AhMpyfKQZcr-1&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=6%3A2&show-proto-sidebar=1). Ver o fluxo "Fluxo inicial do usuário".
